In [1]:
print("Sequence of numbers from 20 to 50:")
vec=seq(20,50)
print("Mean of numbers from 20 to 50:")
print(vec)

[1] "Sequence of numbers from 20 to 50:"
[1] "Mean of numbers from 20 to 50:"
 [1] 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44
[26] 45 46 47 48 49 50

In [2]:
v = sample(-50:50, 10, replace=TRUE)
print("Content of the vector:")
print("10 random integer values between -50 and +50:")
print(v)

[1] "Content of the vector:"
[1] "10 random integer values between -50 and +50:"
 [1] -25  45 -30 -29 -18  -9 -31 -25  22  -8

In [4]:
#first 10 Fibonacci numbers.
Fibonacci <- numeric(30)
Fibonacci[1] <- Fibonacci[2] <- 1
for (i in 3:30) Fibonacci[i] <- Fibonacci[i - 2] + Fibonacci[i - 1]
print("First 10 Fibonacci numbers:")
print(Fibonacci)

[1] "First 10 Fibonacci numbers:"
 [1]      1      1      2      3      5      8     13     21     34     55
[11]     89    144    233    377    610    987   1597   2584   4181   6765
[21]  10946  17711  28657  46368  75025 121393 196418 317811 514229 832040

In [6]:
#all prime numbers up to a given number (based on the sieve of Eratosthenes).
prime_numbers <- function(n) 
{
    if (n >= 2) 
    {
         x = seq(2, n)
         prime_nums = c()
         for (i in seq(2, n)) 
         {
             if (any(x == i)) 
             {
                 prime_nums = c(prime_nums, i)
                 x = c(x[(x %% i) != 0], i)
                 print(x)
             }#if
         }#for
         return(prime_nums)
    }#if
else 
    {
     stop("Input number should be at least 2.")
    }#else
} #function
prime_numbers(10)

[1] 3 5 7 9 2
[1] 5 7 2 3
[1] 7 2 3 5
[1] 2 3 5 7

[1] 2 3 5 7

In [7]:
#extract first 10 english letter in lower case and last 10 letters in upper case and extract 
#letters between 22nd to 24th letters in upper case.
#Use built-in datasets letters and LETTERS.
print("First 10 letters in lower case:")
t = head(letters, 10)
print(t)
print("Last 10 letters in upper case:")
t = tail(LETTERS, 10)
print(t)
print("Letters between 22nd to 24th letters in upper case:")
e = head(LETTERS, 5)
e1 = tail(LETTERS, 5)
print(e)
print(e1)

[1] "First 10 letters in lower case:"
 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j"
[1] "Last 10 letters in upper case:"
 [1] "Q" "R" "S" "T" "U" "V" "W" "X" "Y" "Z"
[1] "Letters between 22nd to 24th letters in upper case:"
[1] "A" "B" "C" "D" "E"
[1] "V" "W" "X" "Y" "Z"

In [8]:
#find the factors of a given number.
print_factors = function(n) 
{
    print(paste("The factors of",n,"are:"))
    for(i in 1:n) 
    {
        if((n %% i) == 0) 
        {
            print(i)
        }#if
    }#for
}#function
print_factors(4)
print_factors(7)
print_factors(12)

[1] "The factors of 4 are:"
[1] 1
[1] 2
[1] 4
[1] "The factors of 7 are:"
[1] 1
[1] 7
[1] "The factors of 12 are:"
[1] 1
[1] 2
[1] 3
[1] 4
[1] 6
[1] 12